release:
  github:
    owner: kim-company
    name: pmux
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
    - make test
builds:
  -
    goos:
      - darwin
      - linux
signs:
  - artifacts: checksum
changelog:
  sort: asc
